version: '3.8'
services:
  scout:
    container_name: chasm_scout
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env

